version: 0.2

phases:
  build:
    commands:
       - mkdir marta/build
       - cp marta/*.py marta/build/
       - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket im-taking-marta-deployments
  artifacts:
    type: zip
    files:
    - packaged.yaml
    discard-paths: no