AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa skill for Marta transit users
Globals:
  Function:
    Timeout: 3
Outputs:
  AlexaFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AlexaFunction
      - Arn
  AlexaFunctionRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - AlexaFunction
      - Arn
Resources:
  AlexaFunction:
    Properties:
      CodeUri: s3://im-taking-marta-deployments/4cac7bb459cc75b32a81925fa9358628
      Environment:
        Variables:
          USER_TABLE_NAME:
            Ref: UserTable
      Events:
        Alexa:
          Type: AlexaSkill
      Handler: app.lambda_handler
      Runtime: python2.7
    Type: AWS::Serverless::Function
  UserTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
