AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa skill for Marta transit tracking
Globals:
  Function:
    Timeout: 3
Outputs:
  AlexaFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AlexaFunction
      - Arn
  AlexaFunctionRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - AlexaFunction
      - Arn
Parameters:
  MartaApiKey:
    Description: API key for MARTA API authentication
    Type: String
Resources:
  AlexaFunction:
    Properties:
      CodeUri: s3://im-taking-marta-deployments/ace378e24268efe16361b14c057a6490
      Environment:
        Variables:
          MARTA_API_KEY:
            Fn::Sub: ${MartaApiKey}
      Events:
        Alexa:
          Type: AlexaSkill
      Handler: app.lambda_handler
      Runtime: python2.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
