AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa skill for Marta transit users
Globals:
    Function:
        Timeout: 3
Resources:
    AlexaFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: marta/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Environment:
                Variables:
                    USER_TABLE_NAME: !Ref UserTable
            Events:
                Alexa:
                    Type: 'AlexaSkill'
    UserTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
            KeySchema:
            - AttributeName: userId
              KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
Outputs:
    AlexaFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt AlexaFunction.Arn

    AlexaFunctionRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt AlexaFunction.Arn
