AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa skill for Marta transit tracking
Globals:
    Function:
        Timeout: 3
Parameters:
    MartaApiKey:
        Type: String
        Description: API key for MARTA API authentication
Resources:
    AlexaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: marta/build/
            Handler: app.lambda_handler
            Runtime: python2.7
            Environment:
                Variables:
                    MARTA_API_KEY: !Sub ${MartaApiKey}
            Events:
                Alexa:
                    Type: AlexaSkill
Outputs:
    AlexaFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt AlexaFunction.Arn

    AlexaFunctionRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt AlexaFunction.Arn
